# Generated by Django 4.0.3 on 2022-05-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mailing',
            table='Mailing',
        ),
    ]
