# Generated by Django 4.0.3 on 2022-05-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id']},
        ),
    ]
